version: '2'
services:
    php7-apache:
        build:
            context: ./
            dockerfile: Dockerfile.php7
        container_name: php7-apache
        restart: always
        ports:
         - "8080:80"
        volumes:
         - ./:/var/www/html
        tty: true

    php56-apache:
        build:
            context: ./
            dockerfile: Dockerfile.php56
        container_name: php56-apache
        restart: always
        ports:
         - "8888:80"
        volumes:
         - ./:/var/www/html
        tty: true

