FROM php:5.6-apache

MAINTAINER Marco Araujo <contact@marcojunior.com>

ENV PATH $PATH:/root/.composer/vendor/bin

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

