version: '2'
services:
    apache:
        build:
            context: .
            dockerfile: dockerfile.apache
        container_name: apache
        restart: always
        ports:
         - "8080:80"
         - "8443:443"
        volumes:
         - html:/usr/local/apache2/htdocs/
         - sites-enabled:/etc/apache2/sites-enabled
        links:
         - php-7
         - php-56

    php-56:
        build:
            context: .
            dockerfile: dockerfile.php56
        container_name: php-56
        restart: always
        ports:
         - "9090:9000"
        volumes:
         - html:/var/www
        links:
         - postgres
         - mongo

    php-7:
        build:
            context: .
            dockerfile: dockerfile.php7
        container_name: php-7
        restart: always
        ports:
         - "9000:9000"
        volumes:
         - html:/var/www
        links:
         - postgres
         - mongo

    node:
        build:
            context: .
            dockerfile: dockerfile.node
        container_name: node
        restart: always
        ports:
         - "3030:3000"
        volumes:
         - html:/var/www
        links:
         - mongo

    postgres:
        build:
            context: .
            dockerfile: dockerfile.postgres
        container_name: postgres
        restart: always
        ports:
         - "54321:5432"
        volumes:
         - postgres:/usr/local/pgsql/data

    mongo:
        build:
            context: .
            dockerfile: dockerfile.mongo
        container_name: mongo
        restart: always
        ports:
         - "27017:27017"
        volumes:
         - mongo:/data/db

    development:
        build:
            context: .
            dockerfile: dockerfile.development
        container_name: development
        restart: always
        ports:
         - "2222:22"
        volumes:
         - html:/projects
         - sites-enabled:/projects/sites-enabled
        links:
         - php-7
         - php-56
         - postgres
         - mongo

volumes:
    html:
        external: true
    mongo:
        external: true
    postgres:
        external: true
    sites-enabled:
        external: true

