version: '2'
services:
    php-7:
        image: php:7.0-apache
        container_name: php-7
        restart: always
        ports:
         - "7080:80"
         - "7443:443"
        volumes:
         - html:/var/www/html
         - sites-enabled:/etc/apache2/sites-enabled
        links:
         - postgres
         - mongo

    php-56:
        image: php:5.6-apache
        container_name: php-56
        restart: always
        ports:
         - "5080:80"
         - "5443:443"
        volumes:
         - html:/var/www/html
         - sites-enabled:/etc/apache2/sites-enabled
        links:
         - postgres
         - mongo

    node:
        build:
            context: .
            dockerfile: dockerfile.node
        container_name: node
        command: [npm, start]
        restart: always
        ports:
         - "8888:8080"
        volumes:
            - html:/html

    postgres:
        image: postgres:9.5
        container_name: postgres
        restart: always
        ports:
         - "54321:5432"
        volumes:
         - postgres:/usr/local/pgsql/data

    mongo:
        image: mongo:3.2
        container_name: mongo
        restart: always
        ports:
         - "27017:27017"
        volumes:
         - mongo:/data/db

    development:
        build:
            context: .
            dockerfile: dockerfile.development
        container_name: development
        restart: always
        ports:
         - "2222:22"
        volumes:
         - html:/projects
         - sites-enabled:/sites-enabled
        volumes_from:
         - php-7:rw
        links:
         - php-56
         - postgres
         - mongo

volumes:
    html:
    mongo:
    postgres:
    sites-enabled:

